//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVUpdateReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", ConfigurationName="NAVUpdateReference.ZRASalesInvoice2_Port")]
    public interface ZRASalesInvoice2_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.Read_Result> ReadAsync(NAVUpdateReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.ReadByRecId_Result> ReadByRecIdAsync(NAVUpdateReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.ReadMultiple_Result> ReadMultipleAsync(NAVUpdateReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.IsUpdated_Result> IsUpdatedAsync(NAVUpdateReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(NAVUpdateReference.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.Create_Result> CreateAsync(NAVUpdateReference.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.CreateMultiple_Result> CreateMultipleAsync(NAVUpdateReference.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.Update_Result> UpdateAsync(NAVUpdateReference.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.UpdateMultiple_Result> UpdateMultipleAsync(NAVUpdateReference.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.Delete_Result> DeleteAsync(NAVUpdateReference.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2:Delete_SalesInvLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVUpdateReference.Delete_SalesInvLines_Result> Delete_SalesInvLinesAsync(NAVUpdateReference.Delete_SalesInvLines request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2")]
    public partial class ZRASalesInvoice2
    {
        
        private string keyField;
        
        private string noField;
        
        private string sell_to_Customer_NameField;
        
        private string sell_to_AddressField;
        
        private string order_ClassField;
        
        private System.DateTime eSD_DateField;
        
        private bool eSD_DateFieldSpecified;
        
        private System.DateTime eSD_TimeField;
        
        private bool eSD_TimeFieldSpecified;
        
        private string invoice_NoField;
        
        private string invoice_CodeField;
        
        private string terminal_IDField;
        
        private string fiscal_CodeField;
        
        private System.DateTime issueTimeField;
        
        private bool issueTimeFieldSpecified;
        
        private decimal transactionTypeField;
        
        private bool transactionTypeFieldSpecified;
        
        private decimal paymentMethodeField;
        
        private bool paymentMethodeFieldSpecified;
        
        private decimal saleTypeField;
        
        private bool saleTypeFieldSpecified;
        
        private string posSerialNumberField;
        
        private string buyerTelField;
        
        private string originalInvoiceCodeField;
        
        private string originalInvoiceNumberField;
        
        private string memoField;
        
        private string buyerTaxAccountNameField;
        
        private bool isTaxInclusiveField;
        
        private bool isTaxInclusiveFieldSpecified;
        
        private string posVendorField;
        
        private string tPINField;
        
        private string taxPayerNameField;
        
        private string addressField;
        
        private string talkTimeField;
        
        private string operatorField;
        
        private bool invoiceSignedField;
        
        private bool invoiceSignedFieldSpecified;
        
        private ESD_Status eSD_StatusField;
        
        private bool eSD_StatusFieldSpecified;
        
        private P_Sales_Inv_Line[] salesInvLinesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sell_to_Customer_Name
        {
            get
            {
                return this.sell_to_Customer_NameField;
            }
            set
            {
                this.sell_to_Customer_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sell_to_Address
        {
            get
            {
                return this.sell_to_AddressField;
            }
            set
            {
                this.sell_to_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Order_Class
        {
            get
            {
                return this.order_ClassField;
            }
            set
            {
                this.order_ClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime ESD_Date
        {
            get
            {
                return this.eSD_DateField;
            }
            set
            {
                this.eSD_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_DateSpecified
        {
            get
            {
                return this.eSD_DateFieldSpecified;
            }
            set
            {
                this.eSD_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=6)]
        public System.DateTime ESD_Time
        {
            get
            {
                return this.eSD_TimeField;
            }
            set
            {
                this.eSD_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_TimeSpecified
        {
            get
            {
                return this.eSD_TimeFieldSpecified;
            }
            set
            {
                this.eSD_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Invoice_No
        {
            get
            {
                return this.invoice_NoField;
            }
            set
            {
                this.invoice_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Invoice_Code
        {
            get
            {
                return this.invoice_CodeField;
            }
            set
            {
                this.invoice_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Terminal_ID
        {
            get
            {
                return this.terminal_IDField;
            }
            set
            {
                this.terminal_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fiscal_Code
        {
            get
            {
                return this.fiscal_CodeField;
            }
            set
            {
                this.fiscal_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime IssueTime
        {
            get
            {
                return this.issueTimeField;
            }
            set
            {
                this.issueTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueTimeSpecified
        {
            get
            {
                return this.issueTimeFieldSpecified;
            }
            set
            {
                this.issueTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionTypeSpecified
        {
            get
            {
                return this.transactionTypeFieldSpecified;
            }
            set
            {
                this.transactionTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal PaymentMethode
        {
            get
            {
                return this.paymentMethodeField;
            }
            set
            {
                this.paymentMethodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentMethodeSpecified
        {
            get
            {
                return this.paymentMethodeFieldSpecified;
            }
            set
            {
                this.paymentMethodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal SaleType
        {
            get
            {
                return this.saleTypeField;
            }
            set
            {
                this.saleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleTypeSpecified
        {
            get
            {
                return this.saleTypeFieldSpecified;
            }
            set
            {
                this.saleTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PosSerialNumber
        {
            get
            {
                return this.posSerialNumberField;
            }
            set
            {
                this.posSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BuyerTel
        {
            get
            {
                return this.buyerTelField;
            }
            set
            {
                this.buyerTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string OriginalInvoiceCode
        {
            get
            {
                return this.originalInvoiceCodeField;
            }
            set
            {
                this.originalInvoiceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string OriginalInvoiceNumber
        {
            get
            {
                return this.originalInvoiceNumberField;
            }
            set
            {
                this.originalInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string BuyerTaxAccountName
        {
            get
            {
                return this.buyerTaxAccountNameField;
            }
            set
            {
                this.buyerTaxAccountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool isTaxInclusive
        {
            get
            {
                return this.isTaxInclusiveField;
            }
            set
            {
                this.isTaxInclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTaxInclusiveSpecified
        {
            get
            {
                return this.isTaxInclusiveFieldSpecified;
            }
            set
            {
                this.isTaxInclusiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string PosVendor
        {
            get
            {
                return this.posVendorField;
            }
            set
            {
                this.posVendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string TPIN
        {
            get
            {
                return this.tPINField;
            }
            set
            {
                this.tPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string TaxPayerName
        {
            get
            {
                return this.taxPayerNameField;
            }
            set
            {
                this.taxPayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string TalkTime
        {
            get
            {
                return this.talkTimeField;
            }
            set
            {
                this.talkTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool InvoiceSigned
        {
            get
            {
                return this.invoiceSignedField;
            }
            set
            {
                this.invoiceSignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceSignedSpecified
        {
            get
            {
                return this.invoiceSignedFieldSpecified;
            }
            set
            {
                this.invoiceSignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public ESD_Status ESD_Status
        {
            get
            {
                return this.eSD_StatusField;
            }
            set
            {
                this.eSD_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_StatusSpecified
        {
            get
            {
                return this.eSD_StatusFieldSpecified;
            }
            set
            {
                this.eSD_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=30)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public P_Sales_Inv_Line[] SalesInvLines
        {
            get
            {
                return this.salesInvLinesField;
            }
            set
            {
                this.salesInvLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2")]
    public enum ESD_Status
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Signed,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2")]
    public partial class P_Sales_Inv_Line
    {
        
        private string keyField;
        
        private string noField;
        
        private string descriptionField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal amount_Including_VATField;
        
        private bool amount_Including_VATFieldSpecified;
        
        private string taxLabelsField;
        
        private bool taxInclusiveField;
        
        private bool taxInclusiveFieldSpecified;
        
        private decimal rRPField;
        
        private bool rRPFieldSpecified;
        
        private string barcodeField;
        
        private string categoryNameField;
        
        private decimal rateField;
        
        private bool rateFieldSpecified;
        
        private decimal totalAmountField;
        
        private bool totalAmountFieldSpecified;
        
        private string verificationUrlField;
        
        private string verificationQRCodeField;
        
        private decimal taxAmountField;
        
        private bool taxAmountFieldSpecified;
        
        private bool invoiceSignedField;
        
        private bool invoiceSignedFieldSpecified;
        
        private ESD_Status_50018 eSD_StatusField;
        
        private bool eSD_StatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Unit_Price
        {
            get
            {
                return this.unit_PriceField;
            }
            set
            {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified
        {
            get
            {
                return this.unit_PriceFieldSpecified;
            }
            set
            {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Amount_Including_VAT
        {
            get
            {
                return this.amount_Including_VATField;
            }
            set
            {
                this.amount_Including_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_Including_VATSpecified
        {
            get
            {
                return this.amount_Including_VATFieldSpecified;
            }
            set
            {
                this.amount_Including_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TaxLabels
        {
            get
            {
                return this.taxLabelsField;
            }
            set
            {
                this.taxLabelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool TaxInclusive
        {
            get
            {
                return this.taxInclusiveField;
            }
            set
            {
                this.taxInclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxInclusiveSpecified
        {
            get
            {
                return this.taxInclusiveFieldSpecified;
            }
            set
            {
                this.taxInclusiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal RRP
        {
            get
            {
                return this.rRPField;
            }
            set
            {
                this.rRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RRPSpecified
        {
            get
            {
                return this.rRPFieldSpecified;
            }
            set
            {
                this.rRPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CategoryName
        {
            get
            {
                return this.categoryNameField;
            }
            set
            {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateSpecified
        {
            get
            {
                return this.rateFieldSpecified;
            }
            set
            {
                this.rateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmountSpecified
        {
            get
            {
                return this.totalAmountFieldSpecified;
            }
            set
            {
                this.totalAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string VerificationUrl
        {
            get
            {
                return this.verificationUrlField;
            }
            set
            {
                this.verificationUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string VerificationQRCode
        {
            get
            {
                return this.verificationQRCodeField;
            }
            set
            {
                this.verificationQRCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxAmountSpecified
        {
            get
            {
                return this.taxAmountFieldSpecified;
            }
            set
            {
                this.taxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool InvoiceSigned
        {
            get
            {
                return this.invoiceSignedField;
            }
            set
            {
                this.invoiceSignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceSignedSpecified
        {
            get
            {
                return this.invoiceSignedFieldSpecified;
            }
            set
            {
                this.invoiceSignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public ESD_Status_50018 ESD_Status
        {
            get
            {
                return this.eSD_StatusField;
            }
            set
            {
                this.eSD_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_StatusSpecified
        {
            get
            {
                return this.eSD_StatusFieldSpecified;
            }
            set
            {
                this.eSD_StatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2")]
    public enum ESD_Status_50018
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Signed,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2")]
    public partial class ZRASalesInvoice2_Filter
    {
        
        private ZRASalesInvoice2_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ZRASalesInvoice2_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2")]
    public enum ZRASalesInvoice2_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Sell_to_Customer_Name,
        
        /// <remarks/>
        Sell_to_Address,
        
        /// <remarks/>
        Order_Class,
        
        /// <remarks/>
        ESD_Date,
        
        /// <remarks/>
        ESD_Time,
        
        /// <remarks/>
        Invoice_No,
        
        /// <remarks/>
        Invoice_Code,
        
        /// <remarks/>
        Terminal_ID,
        
        /// <remarks/>
        Fiscal_Code,
        
        /// <remarks/>
        IssueTime,
        
        /// <remarks/>
        TransactionType,
        
        /// <remarks/>
        PaymentMethode,
        
        /// <remarks/>
        SaleType,
        
        /// <remarks/>
        PosSerialNumber,
        
        /// <remarks/>
        BuyerTel,
        
        /// <remarks/>
        OriginalInvoiceCode,
        
        /// <remarks/>
        OriginalInvoiceNumber,
        
        /// <remarks/>
        Memo,
        
        /// <remarks/>
        BuyerTaxAccountName,
        
        /// <remarks/>
        isTaxInclusive,
        
        /// <remarks/>
        PosVendor,
        
        /// <remarks/>
        TPIN,
        
        /// <remarks/>
        TaxPayerName,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        TalkTime,
        
        /// <remarks/>
        Operator,
        
        /// <remarks/>
        InvoiceSigned,
        
        /// <remarks/>
        ESD_Status,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public string No;
        
        public Read()
        {
        }
        
        public Read(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2;
        
        public Read_Result()
        {
        }
        
        public Read_Result(NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2)
        {
            this.ZRASalesInvoice2 = ZRASalesInvoice2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2)
        {
            this.ZRASalesInvoice2 = ZRASalesInvoice2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public NAVUpdateReference.ZRASalesInvoice2_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(NAVUpdateReference.ZRASalesInvoice2_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVUpdateReference.ZRASalesInvoice2[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(NAVUpdateReference.ZRASalesInvoice2[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2;
        
        public Create()
        {
        }
        
        public Create(NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2)
        {
            this.ZRASalesInvoice2 = ZRASalesInvoice2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2;
        
        public Create_Result()
        {
        }
        
        public Create_Result(NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2)
        {
            this.ZRASalesInvoice2 = ZRASalesInvoice2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List)
        {
            this.ZRASalesInvoice2_List = ZRASalesInvoice2_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List)
        {
            this.ZRASalesInvoice2_List = ZRASalesInvoice2_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2;
        
        public Update()
        {
        }
        
        public Update(NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2)
        {
            this.ZRASalesInvoice2 = ZRASalesInvoice2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2;
        
        public Update_Result()
        {
        }
        
        public Update_Result(NAVUpdateReference.ZRASalesInvoice2 ZRASalesInvoice2)
        {
            this.ZRASalesInvoice2 = ZRASalesInvoice2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List)
        {
            this.ZRASalesInvoice2_List = ZRASalesInvoice2_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(NAVUpdateReference.ZRASalesInvoice2[] ZRASalesInvoice2_List)
        {
            this.ZRASalesInvoice2_List = ZRASalesInvoice2_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_SalesInvLines", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Delete_SalesInvLines
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public string SalesInvLines_Key;
        
        public Delete_SalesInvLines()
        {
        }
        
        public Delete_SalesInvLines(string SalesInvLines_Key)
        {
            this.SalesInvLines_Key = SalesInvLines_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_SalesInvLines_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", IsWrapped=true)]
    public partial class Delete_SalesInvLines_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_SalesInvLines_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalesinvoice2", Order=0)]
        public bool Delete_SalesInvLines_Result1;
        
        public Delete_SalesInvLines_Result()
        {
        }
        
        public Delete_SalesInvLines_Result(bool Delete_SalesInvLines_Result1)
        {
            this.Delete_SalesInvLines_Result1 = Delete_SalesInvLines_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ZRASalesInvoice2_PortChannel : NAVUpdateReference.ZRASalesInvoice2_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ZRASalesInvoice2_PortClient : System.ServiceModel.ClientBase<NAVUpdateReference.ZRASalesInvoice2_Port>, NAVUpdateReference.ZRASalesInvoice2_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZRASalesInvoice2_PortClient() : 
                base(ZRASalesInvoice2_PortClient.GetDefaultBinding(), ZRASalesInvoice2_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ZRASalesInvoice2_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesInvoice2_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(ZRASalesInvoice2_PortClient.GetBindingForEndpoint(endpointConfiguration), ZRASalesInvoice2_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesInvoice2_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZRASalesInvoice2_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesInvoice2_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZRASalesInvoice2_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesInvoice2_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVUpdateReference.Read_Result> NAVUpdateReference.ZRASalesInvoice2_Port.ReadAsync(NAVUpdateReference.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.Read_Result> ReadAsync(string No)
        {
            NAVUpdateReference.Read inValue = new NAVUpdateReference.Read();
            inValue.No = No;
            return ((NAVUpdateReference.ZRASalesInvoice2_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVUpdateReference.ReadByRecId_Result> NAVUpdateReference.ZRASalesInvoice2_Port.ReadByRecIdAsync(NAVUpdateReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            NAVUpdateReference.ReadByRecId inValue = new NAVUpdateReference.ReadByRecId();
            inValue.recId = recId;
            return ((NAVUpdateReference.ZRASalesInvoice2_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVUpdateReference.ReadMultiple_Result> NAVUpdateReference.ZRASalesInvoice2_Port.ReadMultipleAsync(NAVUpdateReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.ReadMultiple_Result> ReadMultipleAsync(NAVUpdateReference.ZRASalesInvoice2_Filter[] filter, string bookmarkKey, int setSize)
        {
            NAVUpdateReference.ReadMultiple inValue = new NAVUpdateReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((NAVUpdateReference.ZRASalesInvoice2_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVUpdateReference.IsUpdated_Result> NAVUpdateReference.ZRASalesInvoice2_Port.IsUpdatedAsync(NAVUpdateReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            NAVUpdateReference.IsUpdated inValue = new NAVUpdateReference.IsUpdated();
            inValue.Key = Key;
            return ((NAVUpdateReference.ZRASalesInvoice2_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVUpdateReference.GetRecIdFromKey_Result> NAVUpdateReference.ZRASalesInvoice2_Port.GetRecIdFromKeyAsync(NAVUpdateReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            NAVUpdateReference.GetRecIdFromKey inValue = new NAVUpdateReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((NAVUpdateReference.ZRASalesInvoice2_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.Create_Result> CreateAsync(NAVUpdateReference.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.CreateMultiple_Result> CreateMultipleAsync(NAVUpdateReference.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.Update_Result> UpdateAsync(NAVUpdateReference.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.UpdateMultiple_Result> UpdateMultipleAsync(NAVUpdateReference.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVUpdateReference.Delete_Result> NAVUpdateReference.ZRASalesInvoice2_Port.DeleteAsync(NAVUpdateReference.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.Delete_Result> DeleteAsync(string Key)
        {
            NAVUpdateReference.Delete inValue = new NAVUpdateReference.Delete();
            inValue.Key = Key;
            return ((NAVUpdateReference.ZRASalesInvoice2_Port)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVUpdateReference.Delete_SalesInvLines_Result> NAVUpdateReference.ZRASalesInvoice2_Port.Delete_SalesInvLinesAsync(NAVUpdateReference.Delete_SalesInvLines request)
        {
            return base.Channel.Delete_SalesInvLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVUpdateReference.Delete_SalesInvLines_Result> Delete_SalesInvLinesAsync(string SalesInvLines_Key)
        {
            NAVUpdateReference.Delete_SalesInvLines inValue = new NAVUpdateReference.Delete_SalesInvLines();
            inValue.SalesInvLines_Key = SalesInvLines_Key;
            return ((NAVUpdateReference.ZRASalesInvoice2_Port)(this)).Delete_SalesInvLinesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZRASalesInvoice2_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZRASalesInvoice2_Port))
            {
                return new System.ServiceModel.EndpointAddress(System.Configuration.ConfigurationManager.AppSettings.Get("NavisionURL"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZRASalesInvoice2_PortClient.GetBindingForEndpoint(EndpointConfiguration.ZRASalesInvoice2_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZRASalesInvoice2_PortClient.GetEndpointAddress(EndpointConfiguration.ZRASalesInvoice2_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            ZRASalesInvoice2_Port,
        }
    }
}
