//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVReadReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", ConfigurationName="NAVReadReference.SalesInvoiceIntegration_Port")]
    public interface SalesInvoiceIntegration_Port
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration:GetSalesInvoices", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVReadReference.GetSalesInvoices_Result> GetSalesInvoicesAsync(NAVReadReference.GetSalesInvoices request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration:UpdateSalesInvoic" +
            "es", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVReadReference.UpdateSalesInvoices_Result> UpdateSalesInvoicesAsync(NAVReadReference.UpdateSalesInvoices request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50003")]
    public partial class SalesInvHeaders
    {
        
        private SalesInvHeader[] salesInvHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesInvHeader", Order=0)]
        public SalesInvHeader[] SalesInvHeader
        {
            get
            {
                return this.salesInvHeaderField;
            }
            set
            {
                this.salesInvHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50003")]
    public partial class SalesInvHeader
    {
        
        private string no_Field;
        
        private string posNumberSeriesField;
        
        private string posvendorField;
        
        private string issueTimeField;
        
        private string transactionTypeField;
        
        private string paymentModeField;
        
        private string saleTypeField;
        
        private string localPurchaseOrderField;
        
        private string user_IDField;
        
        private string vATRegNoField;
        
        private string buyerNameField;
        
        private string buyerTaxAccountField;
        
        private string buyerAddressField;
        
        private string buyerTelField;
        
        private string originslInvoiceCodeField;
        
        private string originslInvoiceNoField;
        
        private string memoField;
        
        private string tPINField;
        
        private string taxPayerNameField;
        
        private string addressField;
        
        private string esdTimeField;
        
        private string terminalIDField;
        
        private string invoiceCodeField;
        
        private string invoiceNoField;
        
        private string fiscalCodeField;
        
        private string talkTimeField;
        
        private string operatorField;
        
        private string isTaxInclusiveField;
        
        private string invoiceSignedField;
        
        private SalesInvLine[] salesInvLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string No_
        {
            get
            {
                return this.no_Field;
            }
            set
            {
                this.no_Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PosNumberSeries
        {
            get
            {
                return this.posNumberSeriesField;
            }
            set
            {
                this.posNumberSeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Posvendor
        {
            get
            {
                return this.posvendorField;
            }
            set
            {
                this.posvendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IssueTime
        {
            get
            {
                return this.issueTimeField;
            }
            set
            {
                this.issueTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PaymentMode
        {
            get
            {
                return this.paymentModeField;
            }
            set
            {
                this.paymentModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SaleType
        {
            get
            {
                return this.saleTypeField;
            }
            set
            {
                this.saleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LocalPurchaseOrder
        {
            get
            {
                return this.localPurchaseOrderField;
            }
            set
            {
                this.localPurchaseOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string User_ID
        {
            get
            {
                return this.user_IDField;
            }
            set
            {
                this.user_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string VATRegNo
        {
            get
            {
                return this.vATRegNoField;
            }
            set
            {
                this.vATRegNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BuyerName
        {
            get
            {
                return this.buyerNameField;
            }
            set
            {
                this.buyerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BuyerTaxAccount
        {
            get
            {
                return this.buyerTaxAccountField;
            }
            set
            {
                this.buyerTaxAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string BuyerAddress
        {
            get
            {
                return this.buyerAddressField;
            }
            set
            {
                this.buyerAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BuyerTel
        {
            get
            {
                return this.buyerTelField;
            }
            set
            {
                this.buyerTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string OriginslInvoiceCode
        {
            get
            {
                return this.originslInvoiceCodeField;
            }
            set
            {
                this.originslInvoiceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string OriginslInvoiceNo
        {
            get
            {
                return this.originslInvoiceNoField;
            }
            set
            {
                this.originslInvoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TPIN
        {
            get
            {
                return this.tPINField;
            }
            set
            {
                this.tPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string TaxPayerName
        {
            get
            {
                return this.taxPayerNameField;
            }
            set
            {
                this.taxPayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string EsdTime
        {
            get
            {
                return this.esdTimeField;
            }
            set
            {
                this.esdTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TerminalID
        {
            get
            {
                return this.terminalIDField;
            }
            set
            {
                this.terminalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string InvoiceCode
        {
            get
            {
                return this.invoiceCodeField;
            }
            set
            {
                this.invoiceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string InvoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string FiscalCode
        {
            get
            {
                return this.fiscalCodeField;
            }
            set
            {
                this.fiscalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string TalkTime
        {
            get
            {
                return this.talkTimeField;
            }
            set
            {
                this.talkTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string IsTaxInclusive
        {
            get
            {
                return this.isTaxInclusiveField;
            }
            set
            {
                this.isTaxInclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string InvoiceSigned
        {
            get
            {
                return this.invoiceSignedField;
            }
            set
            {
                this.invoiceSignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SalesInvLine", Order=29)]
        public SalesInvLine[] SalesInvLine
        {
            get
            {
                return this.salesInvLineField;
            }
            set
            {
                this.salesInvLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50003")]
    public partial class SalesInvLine
    {
        
        private string typeField;
        
        private string itemIDField;
        
        private string descriptionField;
        
        private string barcodeField;
        
        private string quantityField;
        
        private string unit_PriceField;
        
        private string tax_LabelField;
        
        private string totalAmountField;
        
        private string taxInclusiveField;
        
        private string rRPField;
        
        private string categoryNameField;
        
        private string rateField;
        
        private string taxAmountField;
        
        private string verificationUrlField;
        
        private string verificationQRCodeField;
        
        private string invoiceSignedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemID
        {
            get
            {
                return this.itemIDField;
            }
            set
            {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Unit_Price
        {
            get
            {
                return this.unit_PriceField;
            }
            set
            {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Tax_Label
        {
            get
            {
                return this.tax_LabelField;
            }
            set
            {
                this.tax_LabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TaxInclusive
        {
            get
            {
                return this.taxInclusiveField;
            }
            set
            {
                this.taxInclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RRP
        {
            get
            {
                return this.rRPField;
            }
            set
            {
                this.rRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CategoryName
        {
            get
            {
                return this.categoryNameField;
            }
            set
            {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string VerificationUrl
        {
            get
            {
                return this.verificationUrlField;
            }
            set
            {
                this.verificationUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string VerificationQRCode
        {
            get
            {
                return this.verificationQRCodeField;
            }
            set
            {
                this.verificationQRCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string InvoiceSigned
        {
            get
            {
                return this.invoiceSignedField;
            }
            set
            {
                this.invoiceSignedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50004")]
    public partial class UpdateSalesInvLine
    {
        
        private string docNoField;
        
        private int lineNoField;
        
        private string typeField;
        
        private string itemIDField;
        
        private string tax_LabelField;
        
        private string categoryNameField;
        
        private string rateField;
        
        private string taxAmountField;
        
        private string totalAmountField;
        
        private string verificationUrlField;
        
        private string verificationQRCodeField;
        
        public UpdateSalesInvLine()
        {
            this.lineNoField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocNo
        {
            get
            {
                return this.docNoField;
            }
            set
            {
                this.docNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LineNo
        {
            get
            {
                return this.lineNoField;
            }
            set
            {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemID
        {
            get
            {
                return this.itemIDField;
            }
            set
            {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Tax_Label
        {
            get
            {
                return this.tax_LabelField;
            }
            set
            {
                this.tax_LabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CategoryName
        {
            get
            {
                return this.categoryNameField;
            }
            set
            {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string VerificationUrl
        {
            get
            {
                return this.verificationUrlField;
            }
            set
            {
                this.verificationUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string VerificationQRCode
        {
            get
            {
                return this.verificationQRCodeField;
            }
            set
            {
                this.verificationQRCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50004")]
    public partial class UpdateSalesInvHeader
    {
        
        private string no_Field;
        
        private string tPINField;
        
        private string taxPayerNameField;
        
        private string addressField;
        
        private string esdTimeField;
        
        private string terminalIDField;
        
        private string invoiceCodeField;
        
        private string invoiceNoField;
        
        private string fiscalCodeField;
        
        private string talkTimeField;
        
        private string operatorField;
        
        private string invoiceSignedsField;
        
        private UpdateSalesInvLine[] updateSalesInvLineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string No_
        {
            get
            {
                return this.no_Field;
            }
            set
            {
                this.no_Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TPIN
        {
            get
            {
                return this.tPINField;
            }
            set
            {
                this.tPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TaxPayerName
        {
            get
            {
                return this.taxPayerNameField;
            }
            set
            {
                this.taxPayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string EsdTime
        {
            get
            {
                return this.esdTimeField;
            }
            set
            {
                this.esdTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TerminalID
        {
            get
            {
                return this.terminalIDField;
            }
            set
            {
                this.terminalIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string InvoiceCode
        {
            get
            {
                return this.invoiceCodeField;
            }
            set
            {
                this.invoiceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string InvoiceNo
        {
            get
            {
                return this.invoiceNoField;
            }
            set
            {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FiscalCode
        {
            get
            {
                return this.fiscalCodeField;
            }
            set
            {
                this.fiscalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TalkTime
        {
            get
            {
                return this.talkTimeField;
            }
            set
            {
                this.talkTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string InvoiceSigneds
        {
            get
            {
                return this.invoiceSignedsField;
            }
            set
            {
                this.invoiceSignedsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateSalesInvLine", Order=12)]
        public UpdateSalesInvLine[] UpdateSalesInvLine
        {
            get
            {
                return this.updateSalesInvLineField;
            }
            set
            {
                this.updateSalesInvLineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50004")]
    public partial class UpdateSalesInvHeaders
    {
        
        private UpdateSalesInvHeader[] updateSalesInvHeaderField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateSalesInvHeader", Order=0)]
        public UpdateSalesInvHeader[] UpdateSalesInvHeader
        {
            get
            {
                return this.updateSalesInvHeaderField;
            }
            set
            {
                this.updateSalesInvHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSalesInvoices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", IsWrapped=true)]
    public partial class GetSalesInvoices
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", Order=0)]
        public NAVReadReference.SalesInvHeaders xmlUpdateSalesInvoice;
        
        public GetSalesInvoices()
        {
        }
        
        public GetSalesInvoices(NAVReadReference.SalesInvHeaders xmlUpdateSalesInvoice)
        {
            this.xmlUpdateSalesInvoice = xmlUpdateSalesInvoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSalesInvoices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", IsWrapped=true)]
    public partial class GetSalesInvoices_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", Order=0)]
        public string return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", Order=1)]
        public NAVReadReference.SalesInvHeaders xmlUpdateSalesInvoice;
        
        public GetSalesInvoices_Result()
        {
        }
        
        public GetSalesInvoices_Result(string return_value, NAVReadReference.SalesInvHeaders xmlUpdateSalesInvoice)
        {
            this.return_value = return_value;
            this.xmlUpdateSalesInvoice = xmlUpdateSalesInvoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSalesInvoices", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", IsWrapped=true)]
    public partial class UpdateSalesInvoices
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", Order=0)]
        public NAVReadReference.UpdateSalesInvHeaders xmlUpdateSalesInvoice;
        
        public UpdateSalesInvoices()
        {
        }
        
        public UpdateSalesInvoices(NAVReadReference.UpdateSalesInvHeaders xmlUpdateSalesInvoice)
        {
            this.xmlUpdateSalesInvoice = xmlUpdateSalesInvoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSalesInvoices_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", IsWrapped=true)]
    public partial class UpdateSalesInvoices_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceIntegration", Order=0)]
        public NAVReadReference.UpdateSalesInvHeaders xmlUpdateSalesInvoice;
        
        public UpdateSalesInvoices_Result()
        {
        }
        
        public UpdateSalesInvoices_Result(NAVReadReference.UpdateSalesInvHeaders xmlUpdateSalesInvoice)
        {
            this.xmlUpdateSalesInvoice = xmlUpdateSalesInvoice;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface SalesInvoiceIntegration_PortChannel : NAVReadReference.SalesInvoiceIntegration_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class SalesInvoiceIntegration_PortClient : System.ServiceModel.ClientBase<NAVReadReference.SalesInvoiceIntegration_Port>, NAVReadReference.SalesInvoiceIntegration_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SalesInvoiceIntegration_PortClient() : 
                base(SalesInvoiceIntegration_PortClient.GetDefaultBinding(), SalesInvoiceIntegration_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SalesInvoiceIntegration_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesInvoiceIntegration_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(SalesInvoiceIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), SalesInvoiceIntegration_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesInvoiceIntegration_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SalesInvoiceIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesInvoiceIntegration_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SalesInvoiceIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SalesInvoiceIntegration_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NAVReadReference.GetSalesInvoices_Result> GetSalesInvoicesAsync(NAVReadReference.GetSalesInvoices request)
        {
            return base.Channel.GetSalesInvoicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVReadReference.UpdateSalesInvoices_Result> UpdateSalesInvoicesAsync(NAVReadReference.UpdateSalesInvoices request)
        {
            return base.Channel.UpdateSalesInvoicesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalesInvoiceIntegration_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportCredentialOnly;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SalesInvoiceIntegration_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.8.100:7047/DynamicsNAV/WS/CRONUS International Ltd/Codeunit/SalesI" +
                        "nvoiceIntegration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SalesInvoiceIntegration_PortClient.GetBindingForEndpoint(EndpointConfiguration.SalesInvoiceIntegration_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SalesInvoiceIntegration_PortClient.GetEndpointAddress(EndpointConfiguration.SalesInvoiceIntegration_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            SalesInvoiceIntegration_Port,
        }
    }
}
