//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVCreditMemoReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", ConfigurationName="NAVCreditMemoReference.ZRASalesCreditMemo_Port")]
    public interface ZRASalesCreditMemo_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.Read_Result> ReadAsync(NAVCreditMemoReference.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.ReadByRecId_Result> ReadByRecIdAsync(NAVCreditMemoReference.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.ReadMultiple_Result> ReadMultipleAsync(NAVCreditMemoReference.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.IsUpdated_Result> IsUpdatedAsync(NAVCreditMemoReference.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(NAVCreditMemoReference.GetRecIdFromKey request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.Update_Result> UpdateAsync(NAVCreditMemoReference.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.UpdateMultiple_Result> UpdateMultipleAsync(NAVCreditMemoReference.UpdateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.Delete_Result> DeleteAsync(NAVCreditMemoReference.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo:Delete_SalesCrMemoLines", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.Delete_SalesCrMemoLines_Result> Delete_SalesCrMemoLinesAsync(NAVCreditMemoReference.Delete_SalesCrMemoLines request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo")]
    public partial class ZRASalesCreditMemo
    {
        
        private string keyField;
        
        private string noField;
        
        private string sell_to_Customer_NoField;
        
        private string sell_to_Customer_NameField;
        
        private string sell_to_AddressField;
        
        private string order_ClassField;
        
        private System.DateTime eSD_DateField;
        
        private bool eSD_DateFieldSpecified;
        
        private System.DateTime eSD_TimeField;
        
        private bool eSD_TimeFieldSpecified;
        
        private string invoice_NoField;
        
        private string invoice_CodeField;
        
        private string terminal_IDField;
        
        private string fiscal_CodeField;
        
        private System.DateTime issueTimeField;
        
        private bool issueTimeFieldSpecified;
        
        private decimal transactionTypeField;
        
        private bool transactionTypeFieldSpecified;
        
        private decimal paymentMethodeField;
        
        private bool paymentMethodeFieldSpecified;
        
        private decimal saleTypeField;
        
        private bool saleTypeFieldSpecified;
        
        private string posSerialNumberField;
        
        private string buyerTelField;
        
        private string originalInvoiceCodeField;
        
        private string originalInvoiceNumberField;
        
        private string memoField;
        
        private string buyerTaxAccountNameField;
        
        private bool isTaxInclusiveField;
        
        private bool isTaxInclusiveFieldSpecified;
        
        private string posVendorField;
        
        private string tPINField;
        
        private string taxPayerNameField;
        
        private string addressField;
        
        private string talkTimeField;
        
        private string operatorField;
        
        private bool invoiceSignedField;
        
        private bool invoiceSignedFieldSpecified;
        
        private ESD_Status eSD_StatusField;
        
        private bool eSD_StatusFieldSpecified;
        
        private string verificationUrlField;
        
        private string verificationQRCodeField;
        
        private WS_Sales_Cr_Memo_Line[] salesCrMemoLinesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sell_to_Customer_No
        {
            get
            {
                return this.sell_to_Customer_NoField;
            }
            set
            {
                this.sell_to_Customer_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sell_to_Customer_Name
        {
            get
            {
                return this.sell_to_Customer_NameField;
            }
            set
            {
                this.sell_to_Customer_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sell_to_Address
        {
            get
            {
                return this.sell_to_AddressField;
            }
            set
            {
                this.sell_to_AddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Order_Class
        {
            get
            {
                return this.order_ClassField;
            }
            set
            {
                this.order_ClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime ESD_Date
        {
            get
            {
                return this.eSD_DateField;
            }
            set
            {
                this.eSD_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_DateSpecified
        {
            get
            {
                return this.eSD_DateFieldSpecified;
            }
            set
            {
                this.eSD_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time", Order=7)]
        public System.DateTime ESD_Time
        {
            get
            {
                return this.eSD_TimeField;
            }
            set
            {
                this.eSD_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_TimeSpecified
        {
            get
            {
                return this.eSD_TimeFieldSpecified;
            }
            set
            {
                this.eSD_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Invoice_No
        {
            get
            {
                return this.invoice_NoField;
            }
            set
            {
                this.invoice_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Invoice_Code
        {
            get
            {
                return this.invoice_CodeField;
            }
            set
            {
                this.invoice_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Terminal_ID
        {
            get
            {
                return this.terminal_IDField;
            }
            set
            {
                this.terminal_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Fiscal_Code
        {
            get
            {
                return this.fiscal_CodeField;
            }
            set
            {
                this.fiscal_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime IssueTime
        {
            get
            {
                return this.issueTimeField;
            }
            set
            {
                this.issueTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueTimeSpecified
        {
            get
            {
                return this.issueTimeFieldSpecified;
            }
            set
            {
                this.issueTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionTypeSpecified
        {
            get
            {
                return this.transactionTypeFieldSpecified;
            }
            set
            {
                this.transactionTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal PaymentMethode
        {
            get
            {
                return this.paymentMethodeField;
            }
            set
            {
                this.paymentMethodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentMethodeSpecified
        {
            get
            {
                return this.paymentMethodeFieldSpecified;
            }
            set
            {
                this.paymentMethodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal SaleType
        {
            get
            {
                return this.saleTypeField;
            }
            set
            {
                this.saleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleTypeSpecified
        {
            get
            {
                return this.saleTypeFieldSpecified;
            }
            set
            {
                this.saleTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PosSerialNumber
        {
            get
            {
                return this.posSerialNumberField;
            }
            set
            {
                this.posSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string BuyerTel
        {
            get
            {
                return this.buyerTelField;
            }
            set
            {
                this.buyerTelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string OriginalInvoiceCode
        {
            get
            {
                return this.originalInvoiceCodeField;
            }
            set
            {
                this.originalInvoiceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string OriginalInvoiceNumber
        {
            get
            {
                return this.originalInvoiceNumberField;
            }
            set
            {
                this.originalInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Memo
        {
            get
            {
                return this.memoField;
            }
            set
            {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string BuyerTaxAccountName
        {
            get
            {
                return this.buyerTaxAccountNameField;
            }
            set
            {
                this.buyerTaxAccountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool isTaxInclusive
        {
            get
            {
                return this.isTaxInclusiveField;
            }
            set
            {
                this.isTaxInclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isTaxInclusiveSpecified
        {
            get
            {
                return this.isTaxInclusiveFieldSpecified;
            }
            set
            {
                this.isTaxInclusiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string PosVendor
        {
            get
            {
                return this.posVendorField;
            }
            set
            {
                this.posVendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string TPIN
        {
            get
            {
                return this.tPINField;
            }
            set
            {
                this.tPINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string TaxPayerName
        {
            get
            {
                return this.taxPayerNameField;
            }
            set
            {
                this.taxPayerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string TalkTime
        {
            get
            {
                return this.talkTimeField;
            }
            set
            {
                this.talkTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public bool InvoiceSigned
        {
            get
            {
                return this.invoiceSignedField;
            }
            set
            {
                this.invoiceSignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceSignedSpecified
        {
            get
            {
                return this.invoiceSignedFieldSpecified;
            }
            set
            {
                this.invoiceSignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public ESD_Status ESD_Status
        {
            get
            {
                return this.eSD_StatusField;
            }
            set
            {
                this.eSD_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_StatusSpecified
        {
            get
            {
                return this.eSD_StatusFieldSpecified;
            }
            set
            {
                this.eSD_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string VerificationUrl
        {
            get
            {
                return this.verificationUrlField;
            }
            set
            {
                this.verificationUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string VerificationQRCode
        {
            get
            {
                return this.verificationQRCodeField;
            }
            set
            {
                this.verificationQRCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=33)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public WS_Sales_Cr_Memo_Line[] SalesCrMemoLines
        {
            get
            {
                return this.salesCrMemoLinesField;
            }
            set
            {
                this.salesCrMemoLinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo")]
    public enum ESD_Status
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Signed,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo")]
    public partial class WS_Sales_Cr_Memo_Line
    {
        
        private string keyField;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private string noField;
        
        private string descriptionField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private decimal amount_Including_VATField;
        
        private bool amount_Including_VATFieldSpecified;
        
        private string taxLabelsField;
        
        private bool taxInclusiveField;
        
        private bool taxInclusiveFieldSpecified;
        
        private decimal rRPField;
        
        private bool rRPFieldSpecified;
        
        private string barcodeField;
        
        private string categoryNameField;
        
        private decimal rateField;
        
        private bool rateFieldSpecified;
        
        private decimal totalAmountField;
        
        private bool totalAmountFieldSpecified;
        
        private decimal taxAmountField;
        
        private bool taxAmountFieldSpecified;
        
        private bool invoiceSignedField;
        
        private bool invoiceSignedFieldSpecified;
        
        private ESD_Status_50018 eSD_StatusField;
        
        private bool eSD_StatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Type Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Unit_Price
        {
            get
            {
                return this.unit_PriceField;
            }
            set
            {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified
        {
            get
            {
                return this.unit_PriceFieldSpecified;
            }
            set
            {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Amount_Including_VAT
        {
            get
            {
                return this.amount_Including_VATField;
            }
            set
            {
                this.amount_Including_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Amount_Including_VATSpecified
        {
            get
            {
                return this.amount_Including_VATFieldSpecified;
            }
            set
            {
                this.amount_Including_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TaxLabels
        {
            get
            {
                return this.taxLabelsField;
            }
            set
            {
                this.taxLabelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool TaxInclusive
        {
            get
            {
                return this.taxInclusiveField;
            }
            set
            {
                this.taxInclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxInclusiveSpecified
        {
            get
            {
                return this.taxInclusiveFieldSpecified;
            }
            set
            {
                this.taxInclusiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal RRP
        {
            get
            {
                return this.rRPField;
            }
            set
            {
                this.rRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RRPSpecified
        {
            get
            {
                return this.rRPFieldSpecified;
            }
            set
            {
                this.rRPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CategoryName
        {
            get
            {
                return this.categoryNameField;
            }
            set
            {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RateSpecified
        {
            get
            {
                return this.rateFieldSpecified;
            }
            set
            {
                this.rateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal TotalAmount
        {
            get
            {
                return this.totalAmountField;
            }
            set
            {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalAmountSpecified
        {
            get
            {
                return this.totalAmountFieldSpecified;
            }
            set
            {
                this.totalAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal TaxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxAmountSpecified
        {
            get
            {
                return this.taxAmountFieldSpecified;
            }
            set
            {
                this.taxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool InvoiceSigned
        {
            get
            {
                return this.invoiceSignedField;
            }
            set
            {
                this.invoiceSignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceSignedSpecified
        {
            get
            {
                return this.invoiceSignedFieldSpecified;
            }
            set
            {
                this.invoiceSignedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ESD_Status_50018 ESD_Status
        {
            get
            {
                return this.eSD_StatusField;
            }
            set
            {
                this.eSD_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ESD_StatusSpecified
        {
            get
            {
                return this.eSD_StatusFieldSpecified;
            }
            set
            {
                this.eSD_StatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo")]
    public enum Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        G_L_Account,
        
        /// <remarks/>
        Item,
        
        /// <remarks/>
        Resource,
        
        /// <remarks/>
        Fixed_Asset,
        
        /// <remarks/>
        Charge_Item,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo")]
    public enum ESD_Status_50018
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Signed,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo")]
    public partial class ZRASalesCreditMemo_Filter
    {
        
        private ZRASalesCreditMemo_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ZRASalesCreditMemo_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo")]
    public enum ZRASalesCreditMemo_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Sell_to_Customer_No,
        
        /// <remarks/>
        Sell_to_Customer_Name,
        
        /// <remarks/>
        Sell_to_Address,
        
        /// <remarks/>
        Order_Class,
        
        /// <remarks/>
        ESD_Date,
        
        /// <remarks/>
        ESD_Time,
        
        /// <remarks/>
        Invoice_No,
        
        /// <remarks/>
        Invoice_Code,
        
        /// <remarks/>
        Terminal_ID,
        
        /// <remarks/>
        Fiscal_Code,
        
        /// <remarks/>
        IssueTime,
        
        /// <remarks/>
        TransactionType,
        
        /// <remarks/>
        PaymentMethode,
        
        /// <remarks/>
        SaleType,
        
        /// <remarks/>
        PosSerialNumber,
        
        /// <remarks/>
        BuyerTel,
        
        /// <remarks/>
        OriginalInvoiceCode,
        
        /// <remarks/>
        OriginalInvoiceNumber,
        
        /// <remarks/>
        Memo,
        
        /// <remarks/>
        BuyerTaxAccountName,
        
        /// <remarks/>
        isTaxInclusive,
        
        /// <remarks/>
        PosVendor,
        
        /// <remarks/>
        TPIN,
        
        /// <remarks/>
        TaxPayerName,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        TalkTime,
        
        /// <remarks/>
        Operator,
        
        /// <remarks/>
        InvoiceSigned,
        
        /// <remarks/>
        ESD_Status,
        
        /// <remarks/>
        VerificationUrl,
        
        /// <remarks/>
        VerificationQRCode,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public string No;
        
        public Read()
        {
        }
        
        public Read(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo;
        
        public Read_Result()
        {
        }
        
        public Read_Result(NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo)
        {
            this.ZRASalesCreditMemo = ZRASalesCreditMemo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo)
        {
            this.ZRASalesCreditMemo = ZRASalesCreditMemo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public NAVCreditMemoReference.ZRASalesCreditMemo_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(NAVCreditMemoReference.ZRASalesCreditMemo_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVCreditMemoReference.ZRASalesCreditMemo[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(NAVCreditMemoReference.ZRASalesCreditMemo[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo;
        
        public Update()
        {
        }
        
        public Update(NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo)
        {
            this.ZRASalesCreditMemo = ZRASalesCreditMemo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo;
        
        public Update_Result()
        {
        }
        
        public Update_Result(NAVCreditMemoReference.ZRASalesCreditMemo ZRASalesCreditMemo)
        {
            this.ZRASalesCreditMemo = ZRASalesCreditMemo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVCreditMemoReference.ZRASalesCreditMemo[] ZRASalesCreditMemo_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(NAVCreditMemoReference.ZRASalesCreditMemo[] ZRASalesCreditMemo_List)
        {
            this.ZRASalesCreditMemo_List = ZRASalesCreditMemo_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVCreditMemoReference.ZRASalesCreditMemo[] ZRASalesCreditMemo_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(NAVCreditMemoReference.ZRASalesCreditMemo[] ZRASalesCreditMemo_List)
        {
            this.ZRASalesCreditMemo_List = ZRASalesCreditMemo_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_SalesCrMemoLines", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Delete_SalesCrMemoLines
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public string SalesCrMemoLines_Key;
        
        public Delete_SalesCrMemoLines()
        {
        }
        
        public Delete_SalesCrMemoLines(string SalesCrMemoLines_Key)
        {
            this.SalesCrMemoLines_Key = SalesCrMemoLines_Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_SalesCrMemoLines_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", IsWrapped=true)]
    public partial class Delete_SalesCrMemoLines_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_SalesCrMemoLines_Result", Namespace="urn:microsoft-dynamics-schemas/page/zrasalescreditmemo", Order=0)]
        public bool Delete_SalesCrMemoLines_Result1;
        
        public Delete_SalesCrMemoLines_Result()
        {
        }
        
        public Delete_SalesCrMemoLines_Result(bool Delete_SalesCrMemoLines_Result1)
        {
            this.Delete_SalesCrMemoLines_Result1 = Delete_SalesCrMemoLines_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ZRASalesCreditMemo_PortChannel : NAVCreditMemoReference.ZRASalesCreditMemo_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ZRASalesCreditMemo_PortClient : System.ServiceModel.ClientBase<NAVCreditMemoReference.ZRASalesCreditMemo_Port>, NAVCreditMemoReference.ZRASalesCreditMemo_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ZRASalesCreditMemo_PortClient() : 
                base(ZRASalesCreditMemo_PortClient.GetDefaultBinding(), ZRASalesCreditMemo_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ZRASalesCreditMemo_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesCreditMemo_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(ZRASalesCreditMemo_PortClient.GetBindingForEndpoint(endpointConfiguration), ZRASalesCreditMemo_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesCreditMemo_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ZRASalesCreditMemo_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesCreditMemo_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ZRASalesCreditMemo_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ZRASalesCreditMemo_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.Read_Result> NAVCreditMemoReference.ZRASalesCreditMemo_Port.ReadAsync(NAVCreditMemoReference.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.Read_Result> ReadAsync(string No)
        {
            NAVCreditMemoReference.Read inValue = new NAVCreditMemoReference.Read();
            inValue.No = No;
            return ((NAVCreditMemoReference.ZRASalesCreditMemo_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.ReadByRecId_Result> NAVCreditMemoReference.ZRASalesCreditMemo_Port.ReadByRecIdAsync(NAVCreditMemoReference.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            NAVCreditMemoReference.ReadByRecId inValue = new NAVCreditMemoReference.ReadByRecId();
            inValue.recId = recId;
            return ((NAVCreditMemoReference.ZRASalesCreditMemo_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.ReadMultiple_Result> NAVCreditMemoReference.ZRASalesCreditMemo_Port.ReadMultipleAsync(NAVCreditMemoReference.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.ReadMultiple_Result> ReadMultipleAsync(NAVCreditMemoReference.ZRASalesCreditMemo_Filter[] filter, string bookmarkKey, int setSize)
        {
            NAVCreditMemoReference.ReadMultiple inValue = new NAVCreditMemoReference.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((NAVCreditMemoReference.ZRASalesCreditMemo_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.IsUpdated_Result> NAVCreditMemoReference.ZRASalesCreditMemo_Port.IsUpdatedAsync(NAVCreditMemoReference.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            NAVCreditMemoReference.IsUpdated inValue = new NAVCreditMemoReference.IsUpdated();
            inValue.Key = Key;
            return ((NAVCreditMemoReference.ZRASalesCreditMemo_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.GetRecIdFromKey_Result> NAVCreditMemoReference.ZRASalesCreditMemo_Port.GetRecIdFromKeyAsync(NAVCreditMemoReference.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            NAVCreditMemoReference.GetRecIdFromKey inValue = new NAVCreditMemoReference.GetRecIdFromKey();
            inValue.Key = Key;
            return ((NAVCreditMemoReference.ZRASalesCreditMemo_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.Update_Result> UpdateAsync(NAVCreditMemoReference.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.UpdateMultiple_Result> UpdateMultipleAsync(NAVCreditMemoReference.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.Delete_Result> NAVCreditMemoReference.ZRASalesCreditMemo_Port.DeleteAsync(NAVCreditMemoReference.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.Delete_Result> DeleteAsync(string Key)
        {
            NAVCreditMemoReference.Delete inValue = new NAVCreditMemoReference.Delete();
            inValue.Key = Key;
            return ((NAVCreditMemoReference.ZRASalesCreditMemo_Port)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVCreditMemoReference.Delete_SalesCrMemoLines_Result> NAVCreditMemoReference.ZRASalesCreditMemo_Port.Delete_SalesCrMemoLinesAsync(NAVCreditMemoReference.Delete_SalesCrMemoLines request)
        {
            return base.Channel.Delete_SalesCrMemoLinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVCreditMemoReference.Delete_SalesCrMemoLines_Result> Delete_SalesCrMemoLinesAsync(string SalesCrMemoLines_Key)
        {
            NAVCreditMemoReference.Delete_SalesCrMemoLines inValue = new NAVCreditMemoReference.Delete_SalesCrMemoLines();
            inValue.SalesCrMemoLines_Key = SalesCrMemoLines_Key;
            return ((NAVCreditMemoReference.ZRASalesCreditMemo_Port)(this)).Delete_SalesCrMemoLinesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZRASalesCreditMemo_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ZRASalesCreditMemo_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.8.101:7047/DynamicsNAV/WS/CRONUS International Ltd/Page/ZRASalesCr" +
                        "editMemo");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ZRASalesCreditMemo_PortClient.GetBindingForEndpoint(EndpointConfiguration.ZRASalesCreditMemo_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ZRASalesCreditMemo_PortClient.GetEndpointAddress(EndpointConfiguration.ZRASalesCreditMemo_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            ZRASalesCreditMemo_Port,
        }
    }
}
